name: PL Live Auto Update

on:
  workflow_dispatch:

  schedule:
    - cron: "*/20 * * * *"

permissions:
  contents: write

jobs:
  update-playlist:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install requests
        run: |
          python -m pip install --upgrade pip
          python -m pip install requests

      - name: Run Python
        run: |
          python pl_live.py

      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add "PL Live.m3u"

          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Auto update PL Live"
            git push
          fi
