name: PL Live Auto Update

on:
  workflow_dispatch:

  schedule:
    - cron: '*/20 * * * *'

permissions:
  contents: write

jobs:
  update-playlist:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Requests
        run: pip install requests

      - name: Run Playlist Update
        run: python pl_live.py

      - name: Save Updated Playlist
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add "PL Live.m3u"

          if git diff --cached --quiet; then
            echo "No changes detected."
          else
            git commit -m "Auto update PL Live playlist"
            git push
          fi
