name: Update Ripalc Playlist

on:
  schedule:
    - cron: '*/15 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install requests pycryptodome

      - name: Run script
        env:
          CRIC_KEY_1: ${{ secrets.CRIC_KEY_1 }}
          CRIC_IV_1: ${{ secrets.CRIC_IV_1 }}
          CRIC_KEY_2: ${{ secrets.CRIC_KEY_2 }}
          CRIC_IV_2: ${{ secrets.CRIC_IV_2 }}
        run: python ripalc.py

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

          git add playlist.m3u

          git commit -m "Auto update playlist" || echo "No changes to commit"

          git push
